version: '3.3'

services:
  pg_db:
    image: postgres:13-alpine
    container_name: domen_check_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  tg_bot:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: domen_check_bot
    env_file:
      - .env
    depends_on:
      - pg_db    # Изменено здесь - используем простой массив
    restart: unless-stopped
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=pg_db
      - DB_PORT=5432

networks:
  domen_check_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local